# Generated by Django 5.1.4 on 2024-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggybank', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
