# Generated by Django 5.1.4 on 2024-12-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggybank', '0007_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='notified_80_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='notified_exceeded',
            field=models.BooleanField(default=False),
        ),
    ]
